#spring:
#    jpa:
#        database: POSTGRESQL
#        show-sql: false
#        hibernate.ddl-auto: update
#    datasource:
#        platform: postgres
#        url: jdbc:postgresql://localhost:5432/postgres
#        username: postgres
#        password: toor   
#        driverClassName: org.postgresql.Driver
#server:
#    port: 9090
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Drive 
#    url: jdbc:mysql://localhost:3306/sistemas
#    username: root
#    password: des07_18
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#server:#  port: 9090
